### ISSUE TITLE
Register a second SW on the same scope

### ISSUE THREAD

**Issue by ThomasPerraudin** [Nickersoft/push-fcm-plugin#2]
I already have a service worker on my application, registered on the default scope "./"
It doesn't work with firebase-messaging-sw.js certainly because it is registered on the same scope.
Do you have a solution to register both service workers ?

**Comment by Nickersoft** [comment]
I actually wasn't aware you couldn't have multiple service workers registered in the same scope, though I assume that makes sense. You can change the location of the Firebase service worker script using:

```javascript
Push.config({
  FCM: {
    serviceWorkerLocation: './yourLocation'
  }
});
```

If this helps. That way the scope of the Firebase service worker is limited to a subdirectory. Outside of that, it becomes more of a general service worker registration issue than an issue with this plugin.

**Comment by ThomasPerraudin** [comment]
I agree it's a general issue with service workers. I think it happens when both service workers try to work with the same event listeners.

Changing the serviceWorkerLocation triggers an error :-(
> The path of the provided scope ('/') is not under the max scope allowed ('/scripts/'). Adjust the scope, move the Service Worker script, or use the Service-Worker-Allowed HTTP header to allow the scope.

**Comment by Nickersoft** [comment]
So according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#Why_is_my_service_worker_failing_to_register):

```
The max scope for a service worker is the location of the worker
```

which sounds related to your issue. Could you describe your service worker setup in more detail / provide some code? Are you installing this plugin via NPM?

**Comment by ThomasPerraudin** [comment]
I can provide you the full code : [ccm.zip](https://github.com/Nickersoft/push-fcm-plugin/files/1151940/ccm.zip)
You will find the application service worker at the bottom of app.js

**Comment by Nickersoft** [comment]
Hmm.. unfortunately, it does seem to boil down to the issue of overlapping ServiceWorker scopes. In fact, it seems there is an active discussion going on over on the W3 ServiceWorker spec repo about this very thing (see [here](https://github.com/w3c/ServiceWorker/issues/921) and [here](https://github.com/w3c/ServiceWorker/issues/1085)). The best advice I can give, despite it being untested, is creating a single ServiceWorker called `firebase-messaging-sw.js` that uses the [`importScripts()` method](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts) to import the two ServiceWorkers. You would just have to check to make sure you're not registering it twice. Sorry I can't be of more assistance.. unfortunately, I believe it's one of the limitations of ServiceWorkers. I'd suggest that you alter the scope, but then you wouldn't be able to register notifications from the homepage and whatnot.

**Comment by ThomasPerraudin** [comment]
I've also seen that discution in the W3 repo. And I've tried to use importScripts but it doesn't fix the problem.
I hope the next generation of service workers will be far better, I'm sad to discover these big issues.
